// resources/js/components/AppSidebar.vue
<script setup lang="ts">
import NavFooter from '@/components/NavFooter.vue';
import NavMain from '@/components/NavMain.vue';
import NavUser from '@/components/NavUser.vue';
import NavSubscription from '@/components/NavSubscription.vue';
import Sidebar from '@/components/ui/sidebar/Sidebar.vue';
import SidebarContent from '@/components/ui/sidebar/SidebarContent.vue';
import SidebarFooter from '@/components/ui/sidebar/SidebarFooter.vue';
import SidebarHeader from '@/components/ui/sidebar/SidebarHeader.vue';
import SidebarMenu from '@/components/ui/sidebar/SidebarMenu.vue';
import SidebarMenuButton from '@/components/ui/sidebar/SidebarMenuButton.vue';
import SidebarMenuItem from '@/components/ui/sidebar/SidebarMenuItem.vue';
import { dashboard } from '@/routes';
import { type NavItem } from '@/types';
import { Link } from '@inertiajs/vue3';
import { BookOpen, Folder, LayoutGrid, Send, BarChart2 } from 'lucide-vue-next';
import AppLogo from './AppLogo.vue';

const mainNavItems: NavItem[] = [
    {
        title: 'Dashboard',
        href: dashboard(),
        icon: LayoutGrid,
    },
    {
        title: 'Posts',
        href: '/posts',
        icon: Send,
    },
    {
        title: 'Analytics',
        href: '/posts/analytics',
        icon: BarChart2,
    },
];

const footerNavItems: NavItem[] = [
    {
        title: 'Github Repo',
        href: 'https://github.com/zerexei/posexei',
        icon: Folder,
    },
    {
        title: 'Documentation',
        href: 'https://github.com/zerexei/posexei',
        icon: BookOpen,
    },
];
</script>

<template>
    <Sidebar collapsible="icon" variant="inset">
        <SidebarHeader>
            <SidebarMenu>
                <SidebarMenuItem>
                    <SidebarMenuButton size="lg" as-child>
                        <Link :href="dashboard()">
                            <AppLogo />
                        </Link>
                    </SidebarMenuButton>
                </SidebarMenuItem>
            </SidebarMenu>
        </SidebarHeader>

        <SidebarContent>
            <NavMain :items="mainNavItems" label="Platform" />
        </SidebarContent>

        <SidebarFooter>
            <NavFooter :items="footerNavItems" />
            <NavSubscription />
            <NavUser />
        </SidebarFooter>
    </Sidebar>
    <slot />
</template>

// apps/client/src/components/AppSidebar.tsx
import * as React from 'react';
import { Link } from 'react-router-dom';
import { LayoutGrid, Send, BarChart2, Folder, BookOpen } from 'lucide-react';

import {
    Sidebar,
    SidebarContent,
    SidebarFooter,
    SidebarHeader,
    SidebarMenu,
    SidebarMenuButton,
    SidebarMenuItem,
} from '@/components/ui/sidebar';
import { AppLogo } from '@/components/AppLogo';
import { NavMain } from '@/components/NavMain';
import { NavFooter } from '@/components/NavFooter';
import { NavSubscription } from '@/components/NavSubscription';
import { NavUser } from '@/components/NavUser';
import type { NavItem } from '@/types';

const mainNavItems: NavItem[] = [
    {
        title: 'Dashboard',
        href: '/dashboard',
        icon: LayoutGrid,
    },
    {
        title: 'Posts',
        href: '/posts',
        icon: Send,
    },
    {
        title: 'Analytics',
        href: '/posts/analytics',
        icon: BarChart2,
    },
];

const footerNavItems: NavItem[] = [
    {
        title: 'Github Repo',
        href: 'https://github.com/zerexei/posexei',
        icon: Folder,
    },
    {
        title: 'Documentation',
        href: 'https://github.com/zerexei/posexei',
        icon: BookOpen,
    },
];

export const AppSidebar: React.FC = () => {
    return (
        <Sidebar collapsible="icon" variant="inset">
            <SidebarHeader>
                <SidebarMenu>
                    <SidebarMenuItem>
                        <Link to="/dashboard">
                            <SidebarMenuButton size="lg" className="hover:bg-muted transition-all rounded-xl">
                                <AppLogo />
                            </SidebarMenuButton>
                        </Link>
                    </SidebarMenuItem>
                </SidebarMenu>
            </SidebarHeader>

            <SidebarContent>
                <NavMain items={mainNavItems} label="Platform" />
            </SidebarContent>

            <SidebarFooter>
                <NavFooter items={footerNavItems} />
                <NavSubscription />
                <NavUser />
            </SidebarFooter>
        </Sidebar>
    );
};
