// resources/js/components/UserInfo.vue
<script setup lang="ts">
import Avatar from '@/components/ui/avatar/Avatar.vue';
import AvatarFallback from '@/components/ui/avatar/AvatarFallback.vue';
import AvatarImage from '@/components/ui/avatar/AvatarImage.vue';
import { useInitials } from '@/composables/useInitials';
import type { User } from '@/types';
import { computed } from 'vue';

interface Props {
    user: User;
    showEmail?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
    showEmail: false,
});

const { getInitials } = useInitials();

// Compute whether we should show the avatar image
const showAvatar = computed(() => props.user.avatar && props.user.avatar !== '');
</script>

<template>
    <Avatar class="h-8 w-8 overflow-hidden rounded-full border border-border/50 shadow-sm">
        <AvatarImage v-if="showAvatar" :src="'/storage/' + user.avatar!" :alt="user.name" />
        <AvatarFallback class="rounded-full bg-muted font-black text-[10px] text-foreground">
            {{ getInitials(user.name) }}
        </AvatarFallback>
    </Avatar>

    <div class="grid flex-1 text-left text-[11px] leading-tight ml-2">
        <span class="truncate font-black uppercase tracking-widest text-foreground">{{ user.name }}</span>
        <span v-if="showEmail" class="truncate text-[10px] font-bold text-muted-foreground/60 uppercase tracking-tighter">{{ user.email }}</span>
    </div>
</template>

// apps/client/src/components/UserInfo.tsx
import * as React from 'react';
import type { User } from '@/types';
import { getInitials } from '@/lib/initials';

interface Props {
    user: User;
    showEmail?: boolean;
}

export const UserInfo: React.FC<Props> = ({ user, showEmail = false }) => {
    const showAvatar = user.avatar && user.avatar !== '';

    return (
        <div className="flex items-center">
            <div className="h-8 w-8 overflow-hidden rounded-full border border-border/50 shadow-sm bg-muted flex items-center justify-center shrink-0">
                {showAvatar ? (
                    <img src={user.avatar} alt={user.name} className="h-full w-full object-cover" />
                ) : (
                    <span className="font-black text-[10px] text-foreground">
                        {getInitials(user.name)}
                    </span>
                )}
            </div>

            <div className="grid flex-1 text-left text-[11px] leading-tight ml-2 overflow-hidden">
                <span className="truncate font-black uppercase tracking-widest text-foreground">{user.name}</span>
                {showEmail && (
                    <span className="truncate text-[10px] font-bold text-muted-foreground/60 uppercase tracking-tighter">
                        {user.email}
                    </span>
                )}
            </div>
        </div>
    );
};
