// apps/client/src/pages/posts/Show.tsx
import * as React from 'react';
import { useParams, Link } from 'react-router-dom';
import { 
    ChevronLeft, 
    Edit2, 
    BarChart2, 
    Calendar, 
    Globe, 
    History, 
    MessageSquare, 
    Heart, 
    Eye,
    Zap
} from 'lucide-react';
import { Instagram, Twitter, Linkedin, Facebook } from '@/components/SocialIcons';
import { AppLayout } from '@/layouts/AppLayout';
import { 
    Button, 
    Card, 
    CardContent, 
    CardHeader, 
    CardTitle, 
    CardDescription,
    Badge 
} from '@/components/ui/core';
import { cn } from '@/lib/utils';
import { useTitle } from '@/hooks/use-title';

const getPlatformIcon = (id: string) => {
    switch (id) {
        case 'instagram': return Instagram;
        case 'twitter': return Twitter;
        case 'facebook': return Facebook;
        case 'linkedin': return Linkedin;
        default: return Globe;
    }
};

const getBrandColor = (id: string) => {
    switch (id) {
        case 'instagram': return 'text-pink-600 bg-pink-50 dark:bg-pink-950/30';
        case 'twitter': return 'text-sky-500 bg-sky-50 dark:bg-sky-950/30';
        case 'facebook': return 'text-blue-600 bg-blue-50 dark:bg-blue-950/30';
        case 'linkedin': return 'text-blue-700 bg-indigo-50 dark:bg-indigo-950/30';
        default: return 'text-primary bg-primary/10';
    }
}

export const PostShow: React.FC = () => {
    const { id } = useParams<{ id: string }>();
    useTitle('Post Details');

    // Mock Data mimicking the original Show.vue
    const post = {
        id: id || '1',
        title: 'Launch Announcement',
        content: 'We are excited to announce the launch of our new Social Post Manager! 🚀 Manage all your social media channels from one place with advanced analytics and AI-powered content generation. #socialmedia #saas #launch #productivity',
        type: 'text',
        status: 'published',
        platforms: [
            { id: 'instagram', name: 'Instagram', status: 'success', link: '#', likes: '425', comments: '32' },
            { id: 'twitter', name: 'X (Twitter)', status: 'success', link: '#', likes: '128', comments: '14' },
            { id: 'linkedin', name: 'LinkedIn', status: 'success', link: '#', likes: '89', comments: '7' }
        ],
        created_at: '2026-02-27 10:00:00',
        published_at: '2026-02-27 10:05:00',
        engagement: '1.2k',
        reach: '8.4k',
        impressions: '12.5k'
    };

    const breadcrumbs = [
        { title: 'Posts', href: '/posts' },
        { title: 'Post Details', href: `/posts/${id}` },
    ];

    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <div className="flex flex-col gap-8 p-6 max-w-7xl w-full mx-auto pb-20 animate-in fade-in duration-700 slide-in-from-bottom-4">
                {/* Header Section */}
                <div className="flex flex-col sm:flex-row sm:items-center gap-6 justify-between text-left">
                    <div className="flex items-center gap-6">
                        <Link to="/posts">
                            <Button variant="outline" size="icon" className="h-12 w-12 rounded-2xl bg-card border border-border shadow-sm hover:bg-muted transition-all">
                                <ChevronLeft className="w-6 h-6" />
                            </Button>
                        </Link>
                        <div className="space-y-1">
                            <h1 className="text-3xl font-black tracking-tight text-foreground">{post.title}</h1>
                            <div className="flex items-center gap-3 mt-1.5">
                                <Badge variant="success" className="rounded-full px-4 py-1 font-black text-[9px] uppercase tracking-widest border-emerald-500/20">Published</Badge>
                                <span className="text-[10px] text-muted-foreground font-black uppercase tracking-widest opacity-40">System ID: #{post.id}</span>
                            </div>
                        </div>
                    </div>
                    <div className="flex items-center gap-3">
                        <Link to="/posts/analytics">
                            <Button variant="outline" className="h-12 px-6 bg-card border border-border shadow-sm rounded-2xl font-bold gap-2 active:scale-95 transition-all outline-none">
                                <BarChart2 className="w-4 h-4 opacity-70" />
                                Full Analysis
                            </Button>
                        </Link>
                        <Button className="h-12 px-8 rounded-2xl shadow-lg shadow-primary/20 font-bold gap-2 active:scale-95 transition-all outline-none">
                            <Edit2 className="w-4 h-4" />
                            Edit Publication
                        </Button>
                    </div>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
                    {/* Main Content Column */}
                    <div className="lg:col-span-8 space-y-8">
                        <Card className="rounded-[2.5rem] border-border/60 bg-card shadow-sm overflow-hidden text-left border">
                            <CardHeader className="p-8 border-b border-border/10 bg-muted/10">
                                <CardTitle className="text-sm font-black uppercase tracking-[0.2em] text-muted-foreground">Content Core</CardTitle>
                            </CardHeader>
                            <CardContent className="p-0">
                                <div className="p-10 whitespace-pre-wrap text-xl leading-relaxed text-foreground font-medium italic">
                                    "{post.content}"
                                </div>
                                <div className="px-10 py-8 bg-muted/5 border-t border-border/20 flex flex-wrap gap-3">
                                    {['socialmedia', 'saas', 'launch', 'productivity'].map(tag => (
                                        <Badge key={tag} variant="secondary" className="rounded-full bg-card border border-border/60 text-muted-foreground px-4 py-2 font-bold text-[10px] uppercase tracking-widest hover:bg-muted transition-colors">
                                            #{tag}
                                        </Badge>
                                    ))}
                                </div>
                            </CardContent>
                        </Card>

                        <div className="space-y-4">
                            <h3 className="text-[11px] font-black uppercase tracking-[0.2em] text-muted-foreground px-2">Ecosystem Distribution</h3>
                            <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
                                {post.platforms.map(platform => {
                                    const Icon = getPlatformIcon(platform.id);
                                    const colors = getBrandColor(platform.id);
                                    return (
                                        <Card key={platform.id} className="rounded-3xl border-border/60 bg-card hover:bg-muted/10 transition-all group overflow-hidden border shadow-xs">
                                            <CardContent className="p-6 space-y-6 text-left">
                                                <div className="flex items-center justify-between">
                                                    <div className={cn('w-12 h-12 rounded-2xl flex items-center justify-center shadow-inner transition-transform group-hover:scale-110 duration-500 border border-transparent', colors)}>
                                                        <Icon className="w-6 h-6 stroke-[2.5px]" />
                                                    </div>
                                                    <Badge variant="success" className="h-6 text-[9px] font-black rounded-full uppercase tracking-widest px-3 bg-emerald-500/10 text-emerald-600 border-0">Live</Badge>
                                                </div>
                                                <div className="space-y-1">
                                                    <p className="font-extrabold text-sm text-foreground">{platform.name}</p>
                                                    <p className="text-[10px] text-muted-foreground font-black uppercase tracking-widest opacity-40">Success Phase</p>
                                                </div>
                                                <div className="flex items-center justify-between pt-5 border-t border-border/20">
                                                    <div className="flex items-center gap-4">
                                                        <div className="flex items-center gap-2 text-xs font-black text-foreground tabular-nums">
                                                            <Heart className="w-4 h-4 text-rose-500" /> {platform.likes}
                                                        </div>
                                                        <div className="flex items-center gap-2 text-xs font-black text-foreground tabular-nums">
                                                            <MessageSquare className="w-4 h-4 text-primary" /> {platform.comments}
                                                        </div>
                                                    </div>
                                                    <Button variant="ghost" size="icon" className="h-9 w-9 rounded-xl hover:bg-card border border-transparent hover:border-border transition-all">
                                                        <Eye className="w-4 h-4 opacity-40 group-hover:opacity-100" />
                                                    </Button>
                                                </div>
                                            </CardContent>
                                        </Card>
                                    );
                                })}
                            </div>
                        </div>
                    </div>

                    {/* Meta/Stats Column */}
                    <div className="lg:col-span-4 space-y-8">
                        <Card className="rounded-[2.5rem] border-border/60 bg-card shadow-lg text-left overflow-hidden border">
                            <CardHeader className="p-8 pb-4">
                                <CardTitle className="text-sm font-black uppercase tracking-widest text-muted-foreground opacity-60">Impact Statistics</CardTitle>
                                <CardDescription className="text-[10px] uppercase font-bold text-muted-foreground/30">Aggregated performance</CardDescription>
                            </CardHeader>
                            <CardContent className="p-8 pt-4 space-y-8">
                                <div className="grid grid-cols-2 gap-8">
                                    <div className="space-y-2">
                                        <p className="text-[10px] text-muted-foreground font-black uppercase tracking-widest opacity-40">Impressions</p>
                                        <p className="text-3xl font-black text-foreground tracking-tight tabular-nums">{post.impressions}</p>
                                    </div>
                                    <div className="space-y-2">
                                        <p className="text-[10px] text-muted-foreground font-black uppercase tracking-widest opacity-40">Total Reach</p>
                                        <p className="text-3xl font-black text-foreground tracking-tight tabular-nums">{post.reach}</p>
                                    </div>
                                    <div className="space-y-2">
                                        <p className="text-[10px] text-muted-foreground font-black uppercase tracking-widest opacity-40">Engagement</p>
                                        <p className="text-3xl font-black text-foreground tracking-tight tabular-nums">{post.engagement}</p>
                                    </div>
                                    <div className="space-y-2">
                                        <p className="text-[10px] text-muted-foreground font-black uppercase tracking-widest opacity-40">Impact Rate</p>
                                        <p className="text-3xl font-black text-emerald-500 tracking-tight tabular-nums">4.8%</p>
                                    </div>
                                </div>
                                <Button className="w-full rounded-2xl border-0 bg-primary/5 hover:bg-primary/10 h-14 font-black text-[10px] uppercase tracking-[0.2em] text-primary transition-all shadow-none">
                                    Full Insights Console
                                </Button>
                            </CardContent>
                        </Card>

                        <Card className="rounded-[2.5rem] border-border/60 bg-card shadow-sm text-left border overflow-hidden">
                            <CardHeader className="p-8 pb-4">
                                <CardTitle className="text-sm font-black uppercase tracking-widest text-muted-foreground opacity-60 flex items-center gap-3">
                                    <Zap className="w-4 h-4 text-primary" /> Publication Metadata
                                </CardTitle>
                            </CardHeader>
                            <CardContent className="p-8 pt-4 space-y-8">
                                <div className="flex items-start gap-4 group">
                                    <div className="w-11 h-11 rounded-2xl bg-muted border border-border flex items-center justify-center shrink-0 transition-colors group-hover:bg-primary/5 group-hover:text-primary group-hover:border-primary/20">
                                        <Calendar className="w-5 h-5 opacity-40 group-hover:opacity-100 transition-opacity" />
                                    </div>
                                    <div className="space-y-1">
                                        <p className="text-[9px] text-muted-foreground uppercase font-black tracking-widest opacity-40">Composition Date</p>
                                        <p className="text-sm font-bold text-foreground">{post.created_at}</p>
                                    </div>
                                </div>
                                <div className="flex items-start gap-4 group">
                                    <div className="w-11 h-11 rounded-2xl bg-muted border border-border flex items-center justify-center shrink-0 transition-colors group-hover:bg-primary/5 group-hover:text-primary group-hover:border-primary/20">
                                        <History className="w-5 h-5 opacity-40 group-hover:opacity-100 transition-opacity" />
                                    </div>
                                    <div className="space-y-1">
                                        <p className="text-[9px] text-muted-foreground uppercase font-black tracking-widest opacity-40">Distribution Sync</p>
                                        <p className="text-sm font-bold text-foreground">{post.published_at}</p>
                                    </div>
                                </div>
                                <div className="flex items-start gap-4 group">
                                    <div className="w-11 h-11 rounded-2xl bg-muted border border-border flex items-center justify-center shrink-0 transition-colors group-hover:bg-primary/5 group-hover:text-primary group-hover:border-primary/20">
                                        <Globe className="w-5 h-5 opacity-40 group-hover:opacity-100 transition-opacity" />
                                    </div>
                                    <div className="space-y-1">
                                        <p className="text-[9px] text-muted-foreground uppercase font-black tracking-widest opacity-40">Ecosystem Visibility</p>
                                        <p className="text-sm font-black text-foreground uppercase tracking-widest text-emerald-500">Global Public</p>
                                    </div>
                                </div>
                            </CardContent>
                        </Card>
                    </div>
                </div>
            </div>
        </AppLayout>
    );
};

export default PostShow;

// archive/resources/js/pages/posts/Show.vue
<script setup lang="ts">
import { Head, Link } from '@inertiajs/vue3';
import AppLayout from '@/layouts/AppLayout.vue';
import Button from '@/components/ui/button/Button.vue';
import Card from '@/components/ui/card/Card.vue';
import CardContent from '@/components/ui/card/CardContent.vue';
import CardHeader from '@/components/ui/card/CardHeader.vue';
import CardTitle from '@/components/ui/card/CardTitle.vue';
import Badge from '@/components/ui/badge/Badge.vue';
import { ChevronLeft, Edit2, BarChart2, Calendar, Globe, History, Instagram, Twitter, Linkedin, MessageSquare, Heart, Share2, Eye } from 'lucide-vue-next';

const props = defineProps<{
    id: string;
}>();

const breadcrumbs = [
    { title: 'Posts', href: '/posts' },
    { title: 'Post Details', href: `/posts/${props.id}` },
];

const post = {
    id: props.id,
    title: 'Launch Announcement',
    content: 'We are excited to announce the launch of our new Social Post Manager! 🚀 Manage all your social media channels from one place with advanced analytics and AI-powered content generation. #socialmedia #saas #launch #productivity',
    type: 'text',
    status: 'published',
    platforms: [
        { id: 'instagram', name: 'Instagram', status: 'success', link: '#', likes: '425', comments: '32' },
        { id: 'twitter', name: 'X (Twitter)', status: 'success', link: '#', likes: '128', comments: '14' },
        { id: 'linkedin', name: 'LinkedIn', status: 'success', link: '#', likes: '89', comments: '7' }
    ],
    created_at: '2026-02-27 10:00:00',
    published_at: '2026-02-27 10:05:00',
    engagement: '1.2k',
    reach: '8.4k',
    impressions: '12.5k'
};

const getPlatformIcon = (id: string) => {
    switch (id) {
        case 'instagram': return Instagram;
        case 'twitter': return Twitter;
        case 'linkedin': return Linkedin;
        default: return Globe;
    }
};

</script>

<template>
    <AppLayout :breadcrumbs="breadcrumbs">
        <Head :title="post.title" />

        <div class="flex flex-col gap-6 p-6 max-w-6xl mx-auto">
            <div class="flex flex-col sm:flex-row sm:items-center gap-4 justify-between">
                <div class="flex items-center gap-4">
                    <Link href="/posts">
                        <Button variant="outline" size="icon" class="rounded-full bg-card border border-border shadow-sm">
                            <ChevronLeft class="w-5 h-5" />
                        </Button>
                    </Link>
                    <div>
                        <h1 class="text-2xl font-bold tracking-tight text-foreground">{{ post.title }}</h1>
                        <div class="flex items-center gap-2 mt-1">
                            <Badge variant="success" class="rounded-full px-3">Published</Badge>
                            <span class="text-xs text-muted-foreground font-medium">ID: #{{ post.id }}</span>
                        </div>
                    </div>
                </div>
                <div class="flex items-center gap-2">
                    <Link href="/posts/analytics">
                        <Button variant="outline" class="bg-card border border-border shadow-sm rounded-xl">
                            <BarChart2 class="w-4 h-4 mr-2" />
                            Full Analytics
                        </Button>
                    </Link>
                    <Button class="rounded-xl px-6 shadow-md transition-all hover:translate-y-[-1px]">
                        <Edit2 class="w-4 h-4 mr-2" />
                        Edit Post
                    </Button>
                </div>
            </div>

            <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
                <!-- Main Content -->
                <div class="lg:col-span-2 space-y-6">
                    <Card class="rounded-2xl shadow-sm border border-border bg-card overflow-hidden">
                        <CardHeader class="border-b border-border bg-muted/20">
                            <CardTitle class="text-lg">Content Preview</CardTitle>
                        </CardHeader>
                        <CardContent class="p-0 bg-card">
                            <div class="p-8 whitespace-pre-wrap text-lg leading-relaxed text-foreground">
                                {{ post.content }}
                            </div>
                            <div class="p-6 bg-muted/30 border-t border-border flex flex-wrap gap-2">
                                <Badge v-for="tag in ['socialmedia', 'saas', 'launch', 'productivity']" :key="tag" variant="secondary" class="rounded-full bg-card border border-border text-foreground">
                                    #{{ tag }}
                                </Badge>
                            </div>
                        </CardContent>
                    </Card>

                    <h3 class="text-lg font-bold mt-8 text-foreground">Platform Distribution</h3>
                    <div class="grid grid-cols-1 sm:grid-cols-3 gap-4">
                        <Card v-for="platform in post.platforms" :key="platform.id" class="rounded-2xl shadow-sm border border-border bg-card hover:shadow-md transition-all group">
                            <CardContent class="p-5 space-y-5">
                                <div class="flex items-center justify-between">
                                    <div class="w-11 h-11 rounded-xl bg-primary/10 flex items-center justify-center text-primary group-hover:scale-110 transition-transform">
                                        <component :is="getPlatformIcon(platform.id)" class="w-6 h-6" />
                                    </div>
                                    <Badge variant="success" class="h-5 text-[10px] rounded-full uppercase tracking-widest px-2">Live</Badge>
                                </div>
                                <div>
                                    <p class="font-bold capitalize text-foreground">{{ platform.name }}</p>
                                    <p class="text-xs text-muted-foreground font-medium">Published successfully</p>
                                </div>
                                <div class="flex items-center justify-between pt-4 border-t border-border">
                                    <div class="flex items-center gap-4">
                                        <div class="flex items-center gap-1.5 text-xs font-bold text-foreground">
                                            <Heart class="w-3.5 h-3.5 text-rose-500" /> {{ platform.likes }}
                                        </div>
                                        <div class="flex items-center gap-1.5 text-xs font-bold text-foreground">
                                            <MessageSquare class="w-3.5 h-3.5 text-blue-500" /> {{ platform.comments }}
                                        </div>
                                    </div>
                                    <Button variant="ghost" size="icon" class="h-8 w-8 rounded-full hover:bg-muted">
                                        <Eye class="w-4 h-4" />
                                    </Button>
                                </div>
                            </CardContent>
                        </Card>
                    </div>
                </div>

                <!-- Sidebar Info -->
                <div class="space-y-6">
                    <Card class="rounded-2xl shadow-sm border border-border bg-card">
                        <CardHeader>
                            <CardTitle class="text-lg">Performance Summary</CardTitle>
                        </CardHeader>
                        <CardContent class="space-y-7">
                            <div class="grid grid-cols-2 gap-6">
                                <div class="space-y-1.5">
                                    <p class="text-[10px] text-muted-foreground font-black uppercase tracking-widest">Impressions</p>
                                    <p class="text-2xl font-bold text-foreground">{{ post.impressions }}</p>
                                </div>
                                <div class="space-y-1.5">
                                    <p class="text-[10px] text-muted-foreground font-black uppercase tracking-widest">Reach</p>
                                    <p class="text-2xl font-bold text-foreground">{{ post.reach }}</p>
                                </div>
                                <div class="space-y-1.5">
                                    <p class="text-[10px] text-muted-foreground font-black uppercase tracking-widest">Engagement</p>
                                    <p class="text-2xl font-bold text-foreground">{{ post.engagement }}</p>
                                </div>
                                <div class="space-y-1.5">
                                    <p class="text-[10px] text-muted-foreground font-black uppercase tracking-widest">Avg. Rate</p>
                                    <p class="text-2xl font-bold text-emerald-500">4.8%</p>
                                </div>
                            </div>
                            <Button variant="outline" class="w-full rounded-xl border-border bg-muted/20 hover:bg-muted/50 h-11 font-bold">View Detailed Analytics</Button>
                        </CardContent>
                    </Card>

                    <Card class="rounded-2xl shadow-sm border border-border bg-card">
                        <CardHeader>
                            <CardTitle class="text-lg">Post Details</CardTitle>
                        </CardHeader>
                        <CardContent class="space-y-5">
                            <div class="flex items-center gap-4 group">
                                <div class="p-2.5 rounded-xl bg-muted border border-border transition-colors group-hover:bg-primary/5 group-hover:text-primary group-hover:border-primary/20">
                                    <Calendar class="w-5 h-5" />
                                </div>
                                <div>
                                    <p class="text-[10px] text-muted-foreground uppercase font-black tracking-widest">Created</p>
                                    <p class="text-sm font-bold text-foreground">{{ post.created_at }}</p>
                                </div>
                            </div>
                            <div class="flex items-center gap-4 group">
                                <div class="p-2.5 rounded-xl bg-muted border border-border transition-colors group-hover:bg-primary/5 group-hover:text-primary group-hover:border-primary/20">
                                    <History class="w-5 h-5" />
                                </div>
                                <div>
                                    <p class="text-[10px] text-muted-foreground uppercase font-black tracking-widest">Published</p>
                                    <p class="text-sm font-bold text-foreground">{{ post.published_at }}</p>
                                </div>
                            </div>
                            <div class="flex items-center gap-4 group">
                                <div class="p-2.5 rounded-xl bg-muted border border-border transition-colors group-hover:bg-primary/5 group-hover:text-primary group-hover:border-primary/20">
                                    <Globe class="w-5 h-5" />
                                </div>
                                <div>
                                    <p class="text-[10px] text-muted-foreground uppercase font-black tracking-widest">Visibility</p>
                                    <p class="text-sm font-bold text-foreground uppercase tracking-tight">Public</p>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </div>
        </div>
    </AppLayout>
</template>
