// apps/client/src/components/Breadcrumbs.tsx
import * as React from 'react';
import { Link } from 'react-router-dom';
import type { BreadcrumbItemType } from '@/types';
import { ChevronRight } from 'lucide-react';

export const Breadcrumbs: React.FC<{ breadcrumbs: BreadcrumbItemType[] }> = ({ breadcrumbs }) => {
    return (
        <nav aria-label="Breadcrumb" className="flex">
            <ol className="flex items-center space-x-2">
                {breadcrumbs.map((item, index) => (
                    <li key={index} className="flex items-center">
                        {index > 0 && (
                            <ChevronRight className="h-4 w-4 flex-shrink-0 text-muted-foreground/40 mx-1 scale-75" />
                        )}
                        <span className="text-[10px] font-black uppercase tracking-[0.2em]">
                            {index === breadcrumbs.length - 1 ? (
                                <span className="text-foreground">{item.title}</span>
                            ) : (
                                <Link to={item.href} className="text-muted-foreground/60 hover:text-primary transition-colors">
                                    {item.title}
                                </Link>
                            )}
                        </span>
                    </li>
                ))}
            </ol>
        </nav>
    );
};

// archive/resources/js/components/Breadcrumbs.vue
<script setup lang="ts">
import Breadcrumb from '@/components/ui/breadcrumb/Breadcrumb.vue';
import BreadcrumbItem from '@/components/ui/breadcrumb/BreadcrumbItem.vue';
import BreadcrumbLink from '@/components/ui/breadcrumb/BreadcrumbLink.vue';
import BreadcrumbList from '@/components/ui/breadcrumb/BreadcrumbList.vue';
import BreadcrumbPage from '@/components/ui/breadcrumb/BreadcrumbPage.vue';
import BreadcrumbSeparator from '@/components/ui/breadcrumb/BreadcrumbSeparator.vue';
import { Link } from '@inertiajs/vue3';

interface BreadcrumbItemType {
    title: string;
    href?: string;
}

defineProps<{
    breadcrumbs: BreadcrumbItemType[];
}>();
</script>

<template>
    <Breadcrumb>
        <BreadcrumbList>
            <template v-for="(item, index) in breadcrumbs" :key="index">
                <BreadcrumbItem class="text-[10px] font-black uppercase tracking-[0.2em]">
                    <template v-if="index === breadcrumbs.length - 1">
                        <BreadcrumbPage class="text-foreground">{{ item.title }}</BreadcrumbPage>
                    </template>
                    <template v-else>
                        <BreadcrumbLink as-child class="text-muted-foreground/60 hover:text-primary transition-colors">
                            <Link :href="item.href ?? '#'">{{ item.title }}</Link>
                        </BreadcrumbLink>
                    </template>
                </BreadcrumbItem>
                <BreadcrumbSeparator v-if="index !== breadcrumbs.length - 1" class="scale-75 opacity-20" />
            </template>
        </BreadcrumbList>
    </Breadcrumb>
</template>
