// apps/client/src/components/NavUser.tsx
import * as React from 'react';
import { UserInfo } from '@/components/UserInfo';
import { SidebarMenu, SidebarMenuButton, SidebarMenuItem } from '@/components/ui/sidebar';
import { mockUser } from '@/mocks';
import { ChevronsUpDown } from 'lucide-react';

export const NavUser: React.FC = () => {
    const user = mockUser;

    return (
        <SidebarMenu>
            <SidebarMenuItem>
                <SidebarMenuButton
                    size="lg"
                    className="h-12 rounded-2xl transition-all hover:bg-muted data-[state=open]:bg-muted"
                >
                    <UserInfo user={user} />
                    <ChevronsUpDown className="ml-auto size-3.5 opacity-50" />
                </SidebarMenuButton>
            </SidebarMenuItem>
        </SidebarMenu>
    );
};

// archive/resources/js/components/NavUser.vue
<script setup lang="ts">
import UserInfo from '@/components/UserInfo.vue';
import DropdownMenu from '@/components/ui/dropdown-menu/DropdownMenu.vue';
import DropdownMenuContent from '@/components/ui/dropdown-menu/DropdownMenuContent.vue';
import DropdownMenuTrigger from '@/components/ui/dropdown-menu/DropdownMenuTrigger.vue';
import SidebarMenu from '@/components/ui/sidebar/SidebarMenu.vue';
import SidebarMenuButton from '@/components/ui/sidebar/SidebarMenuButton.vue';
import SidebarMenuItem from '@/components/ui/sidebar/SidebarMenuItem.vue';
import { useSidebar } from '@/components/ui/sidebar/utils';
import { usePage } from '@inertiajs/vue3';
import { ChevronsUpDown } from 'lucide-vue-next';
import { computed } from 'vue';
import UserMenuContent from './UserMenuContent.vue';

const page = usePage();
const user = computed(() => page.props.auth.user);
const { isMobile, state } = useSidebar();
</script>

<template>
    <SidebarMenu>
        <SidebarMenuItem>
            <DropdownMenu>
                <DropdownMenuTrigger as-child>
                    <SidebarMenuButton 
                        size="lg" 
                        class="h-12 rounded-2xl transition-all hover:bg-muted data-[state=open]:bg-muted"
                    >
                        <UserInfo :user="user" />
                        <ChevronsUpDown class="ml-auto size-3.5 opacity-50" />
                    </SidebarMenuButton>
                </DropdownMenuTrigger>
                <DropdownMenuContent
                    class="w-(--reka-dropdown-menu-trigger-width) min-w-56 rounded-[1.25rem] shadow-2xl border-border/60 p-2"
                    :side="isMobile ? 'bottom' : state === 'collapsed' ? 'left' : 'bottom'"
                    align="end"
                    :side-offset="8"
                >
                    <UserMenuContent :user="user" />
                </DropdownMenuContent>
            </DropdownMenu>
        </SidebarMenuItem>
    </SidebarMenu>
</template>
