// apps/client/src/pages/auth/Register.tsx
import * as React from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { AuthLayout } from '@/layouts/AuthLayout';
import { Button, Input, Label, Card, CardContent } from '@/components/ui/core';

export const Register: React.FC = () => {
    const navigate = useNavigate();
    const [isLoading, setIsLoading] = React.useState(false);

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        setIsLoading(true);
        // Simulate registration
        setTimeout(() => {
            setIsLoading(false);
            navigate('/dashboard');
        }, 1200);
    };

    return (
        <AuthLayout 
            title="Create an account" 
            description="Enter your details below to create your account"
        >
            <div className="grid gap-6 animate-in fade-in slide-in-from-bottom-2 duration-600">
                 <Card className="border-border shadow-2xl shadow-black/5 rounded-[2rem] overflow-hidden bg-card">
                    <CardContent className="p-8 space-y-6">
                        <form onSubmit={handleSubmit} className="space-y-4">
                            <div className="space-y-4">
                                <div className="space-y-2 text-left">
                                    <Label htmlFor="name" className="text-[10px] font-black uppercase tracking-widest text-muted-foreground/60 px-1">Full Name</Label>
                                    <Input 
                                        id="name" 
                                        type="text" 
                                        placeholder="John Doe" 
                                        required 
                                        className="h-11 rounded-xl border-border bg-muted/20 focus-visible:ring-primary/10 px-4"
                                    />
                                </div>
                                <div className="space-y-2 text-left">
                                    <Label htmlFor="email" className="text-[10px] font-black uppercase tracking-widest text-muted-foreground/60 px-1">Email Address</Label>
                                    <Input 
                                        id="email" 
                                        type="email" 
                                        placeholder="name@example.com" 
                                        required 
                                        className="h-11 rounded-xl border-border bg-muted/20 focus-visible:ring-primary/10 px-4"
                                    />
                                </div>
                                <div className="space-y-2 text-left">
                                    <Label htmlFor="password" title="Password" className="text-[10px] font-black uppercase tracking-widest text-muted-foreground/60 px-1">Password</Label>
                                    <Input 
                                        id="password" 
                                        type="password" 
                                        required 
                                        className="h-11 rounded-xl border-border bg-muted/20 focus-visible:ring-primary/10 px-4"
                                    />
                                </div>
                            </div>
                            <Button 
                                type="submit" 
                                className="w-full h-12 rounded-xl font-bold shadow-lg shadow-primary/10 transition-all hover:scale-[1.02] active:scale-95 border-0 mt-4"
                                disabled={isLoading}
                            >
                                {isLoading ? 'Creating Account...' : 'Continue'}
                            </Button>
                        </form>
                    </CardContent>
                </Card>

                <p className="px-8 text-center text-xs text-muted-foreground font-medium leading-relaxed">
                    By clicking continue, you agree to our{' '}
                    <Link to="#" className="font-black text-primary hover:underline">Terms of Service</Link>{' '}
                    and{' '}
                    <Link to="#" className="font-black text-primary hover:underline">Privacy Policy</Link>.
                </p>

                <p className="text-center text-xs text-muted-foreground font-medium">
                    Already have an account?{' '}
                    <Link to="/login" className="font-black text-primary hover:underline">
                        Sign in
                    </Link>
                </p>
            </div>
        </AuthLayout>
    );
};

export default Register;

// resources/js/pages/auth/Register.vue
<script setup lang="ts">
import RegisteredUserController from '@/actions/App/Http/Controllers/Auth/RegisteredUserController';
import InputError from '@/components/InputError.vue';
import TextLink from '@/components/TextLink.vue';
import Button from '@/components/ui/button/Button.vue';
import Input from '@/components/ui/input/Input.vue';
import Label from '@/components/ui/label/Label.vue';
import AuthBase from '@/layouts/AuthLayout.vue';
import { login } from '@/routes';
import { Form, Head } from '@inertiajs/vue3';
import { LoaderCircle } from 'lucide-vue-next';
</script>

<template>
    <AuthBase title="Create an account" description="Enter your details below to create your account">
        <Head title="Register" />

        <Form
            v-bind="RegisteredUserController.store.form()"
            :reset-on-success="['password', 'password_confirmation']"
            v-slot="{ errors, processing }"
            class="flex flex-col gap-6"
        >
            <div class="grid gap-6">
                <div class="grid gap-2">
                    <Label for="name">Name</Label>
                    <Input id="name" type="text" required autofocus :tabindex="1" autocomplete="name" name="name" placeholder="Full name" />
                    <InputError :message="errors.name" />
                </div>

                <div class="grid gap-2">
                    <Label for="email">Email address</Label>
                    <Input id="email" type="email" required :tabindex="2" autocomplete="email" name="email" placeholder="email@example.com" />
                    <InputError :message="errors.email" />
                </div>

                <div class="grid gap-2">
                    <Label for="password">Password</Label>
                    <Input id="password" type="password" required :tabindex="3" autocomplete="new-password" name="password" placeholder="Password" />
                    <InputError :message="errors.password" />
                </div>

                <div class="grid gap-2">
                    <Label for="password_confirmation">Confirm password</Label>
                    <Input
                        id="password_confirmation"
                        type="password"
                        required
                        :tabindex="4"
                        autocomplete="new-password"
                        name="password_confirmation"
                        placeholder="Confirm password"
                    />
                    <InputError :message="errors.password_confirmation" />
                </div>

                <Button type="submit" class="mt-2 w-full" tabindex="5" :disabled="processing">
                    <LoaderCircle v-if="processing" class="h-4 w-4 animate-spin" />
                    Create account
                </Button>
            </div>

            <div class="text-center text-sm text-muted-foreground">
                Already have an account?
                <TextLink :href="login()" class="underline underline-offset-4" :tabindex="6">Log in</TextLink>
            </div>
        </Form>
    </AuthBase>
</template>
